---
title: "課?<a0>?練習模<e7><89><88>"
author: "???L?F"
date: "2020-10-14"
output: output_format
params:
  id: "410973073"
---
```{r}
```


```{r}
1+1.5
```

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```




```{r}
num <- c(1.5, 2, 3)
int <- c(1L, 3L, -2L)
char <- c("1.5","2","3")
logi <- c(T,T,F)

typeof(num)
typeof(int)
typeof(char)
typeof(logi)
```
```{r}
```


```{r haha}
# 10位學生的主系
majors10_char <- c('經濟學系','社會學系','社會學系','經濟學系','經濟學系','社會學系','經濟學系','經濟學系','經濟學系','社會學系')

typeof(majors10_char)
class(majors10_char)
```
##------------------------------------------------------------------------
```{r}
majors10_factor <- factor(majors10_char)
# 或
majors10_factor <- factor(
  c('經濟學系','社會學系','社會學系','經濟學系','經濟學系','社會學系','經濟學系','經濟學系','經濟學系','社會學系')
)

typeof(majors10_factor)
class(majors10_factor)
```
##-----------------------------------------------------------------------
```{r}                              
class(1
    )
```
```{r}
class("1")

 class({1})

as.numeric("1")

 a <- "1"
 as.numeric(a)

```
```{r}
as.numeric(a)+1

```
```{r}
majors.10_char
majors10_factor
```
```{r}
as.integer(majors10_factor)
```
```{r}
a <- factor(c("一","二","三"))
a
```

